export declare class BasicTokenizer {
    private iPos;
    private iLine;
    private iLineEnd;
    private sInput;
    private oDebug;
    private fnNum8Dec;
    private fnNum16Dec;
    private fnNum32Dec;
    private fnNum8DecAsStr;
    private fnNum16DecAsStr;
    private fnNum16Bin;
    private fnNum16Hex;
    private fnNumFp;
    private fnGetBit7TerminatedString;
    private fnVar;
    private fnIntVar;
    private fnStringVar;
    private fnFpVar;
    private fnRsx;
    private fnStringUntilEol;
    private fnApostrophe;
    private fnRem;
    private fnQuotedString;
    private mTokens;
    private mTokensFF;
    private debugPrintInfo;
    private debugCollectInfo;
    private fnParseLineFragment;
    private fnParseNextLine;
    private fnParseProgram;
    decodeLineFragment(sProgram: string, iOffset: number, iLength: number): string;
    decode(sProgram: string): string;
}
