export interface CanvasOptions {
    aCharset: number[][];
    onClickKey?: (arg0: string) => void;
}
export declare class Canvas {
    fnUpdateCanvasHandler: undefined;
    fnUpdateCanvas2Handler: undefined;
    iFps: number;
    iTextFpsCounter: number;
    cpcAreaBox: any;
    textText: any;
    aCharset: number[][];
    onClickKey?: (arg0: string) => void;
    iGColMode: number;
    bClipped: boolean;
    iMask: number;
    iMaskBit: number;
    iMaskFirst: number;
    iOffset: number;
    canvas: any;
    iWidth: number;
    iHeight: number;
    iBorderWidth: number;
    dataset8: any;
    bNeedUpdate: boolean;
    bNeedTextUpdate: boolean;
    aColorValues: number[][];
    aCurrentInks: any[];
    aSpeedInk: any[];
    aPen2ColorMap: any[];
    animationTimeout: any;
    animationFrame: any;
    imageData: any;
    fnCopy2Canvas: any;
    bLittleEndian: boolean;
    aPen2Color32: any;
    aData32: any;
    bUse32BitCopy: boolean;
    iGPen: any;
    iGPaper: any;
    iInkSet: number;
    iSpeedInkCount: number;
    oCustomCharset: {};
    aTextBuffer: any[];
    bHasFocus: boolean;
    oModeData: any;
    iMode: number;
    xPos: number;
    yPos: number;
    xOrig: number;
    yOrig: number;
    xLeft: number;
    xRight: number;
    yTop: number;
    yBottom: number;
    bGTransparent: boolean;
    constructor(options: CanvasOptions);
    private static aColors;
    private static aDefaultInks;
    private static aModeData;
    private static sCpc2Unicode;
    init(options: CanvasOptions): void;
    reset(): void;
    resetCustomChars(): void;
    private resetTextBuffer;
    static isLittleEndian(): boolean;
    static extractColorValues(sColor: string): number[];
    static extractAllColorValues(aColors: string[]): number[][];
    private setAlpha;
    private setNeedUpdate;
    private setNeedTextUpdate;
    private updateCanvas2;
    private updateCanvas;
    startUpdateCanvas(): void;
    stopUpdateCanvas(): void;
    private copy2Canvas8bit;
    private copy2Canvas32bit;
    private copy2Canvas32bitWithOffset;
    setScreenOffset(iOffset: number): void;
    private updateTextWindow;
    private updateColorMap;
    updateSpeedInk(): void;
    setCustomChar(iChar: number, aCharData: any): void;
    getCharData(iChar: number): any;
    setDefaultInks(): void;
    private setFocusOnCanvas;
    private getMousePos;
    private canvasClickAction2;
    onCpcCanvasClick(event: Event): void;
    onWindowClick(): void;
    getXpos(): number;
    getYpos(): number;
    private fillMyRect;
    fillTextBox(iLeft: number, iTop: number, iWidth: number, iHeight: number, iPen: number): void;
    private moveMyRectUp;
    private moveMyRectDown;
    private invertChar;
    private setChar;
    private readCharData;
    private setSubPixels;
    private setPixel;
    private setPixelOriginIncluded;
    private testSubPixel;
    private testPixel;
    getByte(iAddr: number): number;
    setByte(iAddr: number, iByte: number): void;
    private drawBresenhamLine;
    draw(x: number, y: number): void;
    drawr(x: number, y: number): void;
    move(x: number, y: number): void;
    mover(x: number, y: number): void;
    plot(x: number, y: number): void;
    plotr(x: number, y: number): void;
    test(x: number, y: number): number;
    testr(x: number, y: number): number;
    setInk(iPen: number, iInk1: number, iInk2: number): boolean;
    setBorder(iInk1: number, iInk2: number): void;
    setGPen(iGPen: number): void;
    setGPaper(iGPaper: number): void;
    setGTransparentMode(bTransparent: boolean): void;
    printGChar(iChar: number): void;
    private clearTextBufferBox;
    private copyTextBufferBoxUp;
    private copyTextBufferBoxDown;
    private putCharInTextBuffer;
    private getCharFromTextBuffer;
    printChar(iChar: number, x: number, y: number, iPen: number, iPaper: number, bTransparent: boolean): void;
    drawCursor(x: number, y: number, iPen: number, iPaper: number): void;
    private findMatchingChar;
    readChar(x: number, y: number, iPen: number, iPaper: number): number;
    fill(iFillPen: number): void;
    private static fnPutInRange;
    setOrigin(xOrig: number, yOrig: number): void;
    setGWindow(xLeft: number, xRight: number, yTop: number, yBottom: number): void;
    setGColMode(iGColMode: number): void;
    clearTextWindow(iLeft: number, iRight: number, iTop: number, iBottom: number, iPaper: number): void;
    clearGraphicsWindow(): void;
    clearFullWindow(): void;
    windowScrollUp(iLeft: number, iRight: number, iTop: number, iBottom: number, iPen: number): void;
    windowScrollDown(iLeft: number, iRight: number, iTop: number, iBottom: number, iPen: number): void;
    setSpeedInk(iTime1: number, iTime2: number): void;
    setMask(iMask: number): void;
    setMaskFirst(iMaskFirst: number): void;
    getMode(): number;
    changeMode(iMode: number): void;
    setMode(iMode: number): void;
}
