import { Model } from "./Model";
import { View } from "./View";
export declare class CommonEventHandler {
    static fnEventHandler: undefined;
    model: Model;
    view: View;
    controller: any;
    fnUserAction: any;
    constructor(oModel: any, oView: any, oController: any);
    init(oModel: any, oView: any, oController: any): void;
    fnCommonEventHandler(event: any): void;
    private attachEventHandler;
    toogleHidden(sId: string, sProp: string, sDisplay?: string): boolean;
    fnActivateUserAction(fnAction: any): void;
    fnDeactivateUserAction(): void;
    onSpecialButtonClick(): void;
    onInputButtonClick(): void;
    onInp2ButtonClick(): void;
    onOutputButtonClick(): void;
    onResultButtonClick(): void;
    onTextButtonClick(): void;
    onVariableButtonClick(): void;
    onCpcButtonClick(): void;
    onKbdButtonClick(): void;
    onKbdLayoutButtonClick(): void;
    onConsoleButtonClick(): void;
    onParseButtonClick(): void;
    onRenumButtonClick(): void;
    onPrettyButtonClick(): void;
    fnUpdateAreaText(sInput: any): void;
    onUndoButtonClick(): void;
    onRedoButtonClick(): void;
    onRunButtonClick(): void;
    onStopButtonClick(): void;
    onContinueButtonClick(event: any): void;
    onResetButtonClick(): void;
    onParseRunButtonClick(event: any): void;
    onHelpButtonClick(): void;
    onInputTextClick(): void;
    onOutputTextClick(): void;
    onResultTextClick(): void;
    onVarTextClick(): void;
    onOutputTextChange(): void;
    private encodeUriParam;
    onReloadButtonClick(): void;
    onDatabaseSelectChange(): void;
    onExampleSelectChange(): void;
    onVarSelectChange(): void;
    onKbdLayoutSelectChange(): void;
    onVarTextChange(): void;
    onScreenshotButtonClick(): void;
    onEnterButtonClick(): void;
    onSoundButtonClick(): void;
    onCpcCanvasClick(event: any): void;
    onWindowClick(event: any): void;
}
