import { IController } from "./Interfaces";
import { Model } from "./Model";
import { View } from "./View";
export declare class CommonEventHandler implements EventListenerObject {
    private readonly model;
    private readonly view;
    private readonly controller;
    private fnUserAction;
    constructor(model: Model, view: View, controller: IController);
    fnSetUserAction(fnAction: ((event: Event, id: string) => void) | undefined): void;
    private onInputButtonClick;
    private onInp2ButtonClick;
    private onOutputButtonClick;
    private onResultButtonClick;
    private onVariableButtonClick;
    private onCpcButtonClick;
    private onConvertButtonClick;
    private onSettingsButtonClick;
    private onGalleryButtonClick;
    private onMoreButtonClick;
    private onKbdButtonClick;
    private onConsoleButtonClick;
    private onParseButtonClick;
    private onRenumButtonClick;
    private onPrettyButtonClick;
    private onLineNumberAddButtonClick;
    private onLineNumberRemoveButtonClick;
    private fnUpdateAreaText;
    private onUndoButtonClick;
    private onRedoButtonClick;
    private onDownloadButtonClick;
    private onRunButtonClick;
    private onStopButtonClick;
    private onContinueButtonClick;
    private onResetButtonClick;
    private onParseRunButtonClick;
    private static onHelpButtonClick;
    private onGalleryItemClick;
    private static onNothing;
    private onCopyTextButtonClick;
    private onOutputTextChange;
    private static encodeUriParam;
    private onReloadButtonClick;
    private onDatabaseSelectChange;
    private onDirectorySelectChange;
    private onExampleSelectChange;
    onVarSelectChange(): void;
    onKbdLayoutSelectChange(): void;
    private onBasicVersionSelectChange;
    private onPaletteSelectChange;
    private onCanvasTypeSelectChange;
    private onVarTextChange;
    private onDebugInputChange;
    private onImplicitLinesInputChange;
    private onArrayBoundsInputChange;
    private onConsoleLogInputChange;
    private onTraceInputChange;
    private onAutorunInputChange;
    private onSoundInputChange;
    private onSpeedInputChange;
    private onScreenshotButtonClick;
    private onEnterButtonClick;
    private static onFullscreenButtonClick;
    private onCpcCanvasClick;
    private onWindowClick;
    private onTextTextClick;
    private readonly handlers;
    handleEvent(event: Event): void;
}
//# sourceMappingURL=CommonEventHandler.d.ts.map