import { IController } from "./Interfaces";
import { Model } from "./Model";
import { View } from "./View";
interface CommonEventHandlerOptions {
    model: Model;
    view: View;
    controller: IController;
}
export declare class CommonEventHandler implements EventListenerObject {
    private readonly options;
    private readonly model;
    private readonly view;
    private readonly controller;
    private fnUserAction;
    constructor(options: CommonEventHandlerOptions);
    getOptions(): CommonEventHandlerOptions;
    private setOptions;
    fnSetUserAction(fnAction: ((event: Event, id: string) => void) | undefined): void;
    private onConvertButtonClick;
    private onSettingsButtonClick;
    private onViewButtonClick;
    private onExportButtonClick;
    private onGalleryButtonClick;
    private onMoreButtonClick;
    private onParseButtonClick;
    private onRenumButtonClick;
    private onPrettyButtonClick;
    private onLineNumberAddButtonClick;
    private onLineNumberRemoveButtonClick;
    private fnUpdateAreaText;
    private onUndoButtonClick;
    private onRedoButtonClick;
    private onDownloadButtonClick;
    private onRunButtonClick;
    private onStopButtonClick;
    private onContinueButtonClick;
    private onResetButtonClick;
    private onParseRunButtonClick;
    private static onHelpButtonClick;
    private onGalleryItemClick;
    private static onNothing;
    private onCopyTextButtonClick;
    private onOutputTextChange;
    private static encodeUriParam;
    private onReloadButtonClick;
    private onDatabaseSelectChange;
    private onDirectorySelectChange;
    private onExampleSelectChange;
    onVarSelectChange(): void;
    onKbdLayoutSelectChange(): void;
    private onBasicVersionSelectChange;
    private onPaletteSelectChange;
    private onCanvasTypeSelectChange;
    private onVarTextChange;
    private onDebugInputChange;
    private onImplicitLinesInputChange;
    private onArrayBoundsInputChange;
    private onShowCpcInputChange;
    private onShowKbdInputChange;
    private onShowInp2InputChange;
    private onShowResultInputChange;
    private onShowInputInputChange;
    private onShowVariableInputChange;
    private onShowOutputInputChange;
    private onShowDisassInputChange;
    private onShowConsoleLogInputChange;
    private onDisassInputChange;
    private onTraceInputChange;
    private onAutorunInputChange;
    private onSoundInputChange;
    private onSpeedInputChange;
    private onScreenshotButtonClick;
    private onClearInputButtonClick;
    private onEnterButtonClick;
    private static onFullscreenButtonClick;
    private onCpcCanvasClick;
    private onWindowClick;
    private onTextTextClick;
    private readonly handlers;
    handleEvent(event: Event): void;
}
export {};
//# sourceMappingURL=CommonEventHandler.d.ts.map