import { ViewID } from "./Constants";
import { IController, ICanvas, VariableValue, ICpcVmRsx } from "./Interfaces";
import { VirtualKeyboard } from "./VirtualKeyboard";
import { Model } from "./Model";
import { View } from "./View";
export declare class Controller implements IController {
    private readonly fnRunLoopHandler;
    private readonly fnWaitKeyHandler;
    private readonly fnWaitInputHandler;
    private readonly fnOnEscapeHandler;
    private readonly fnDirectInputHandler;
    private readonly fnPutKeyInBufferHandler;
    private readonly fnOnDragoverHandler;
    private readonly fnOnUserActionHandler;
    private readonly fnWaitForContinueHandler;
    private readonly fnEditLineCallbackHandler;
    private fnScript?;
    private timeoutHandlerActive;
    private nextLoopTimeOut;
    private initialLoopTimeout;
    private inputSet;
    private variables;
    private basicFormatter?;
    private basicTokenizer?;
    private codeGeneratorToken?;
    private codeGeneratorBasic?;
    private readonly model;
    private readonly view;
    private readonly commonEventHandler;
    private readonly basicLexer;
    private readonly basicParser;
    private readonly codeGeneratorJs;
    private readonly canvases;
    private canvas;
    private readonly inputStack;
    private readonly keyboard;
    private virtualKeyboard?;
    private dragElement?;
    private readonly sound;
    private readonly vm;
    private readonly noStop;
    private readonly savedStop;
    private fileHandler?;
    private fileSelect?;
    private hasStorageDatabase;
    private z80Disass?;
    constructor(model: Model, view: View);
    private static readonly codeGenJsBasicParserOptions;
    private static readonly codeGenTokenBasicParserOptions;
    private static readonly formatterBasicParserOptions;
    private initDatabases;
    private onUserAction;
    addIndex(dir: string, input: string): void;
    addItem(key: string, input: string): string;
    addRsx(key: string, RsxConstructor: new () => ICpcVmRsx): string;
    private setDatabaseSelectOptions;
    private static getPathFromExample;
    private static getNameFromExample;
    private setDirectorySelectOptions;
    setExampleSelectOptions(): void;
    setGalleryAreaInputs(): void;
    private static fnSortByStringProperties;
    private setVarSelectOptions;
    private static readonly exportEditorText;
    setExportSelectOptions(select: ViewID): void;
    private updateStorageDatabase;
    private removeKeyBoardHandler;
    setInputText(input: string, keepStack?: boolean): void;
    invalidateScript(): void;
    private fnWaitForContinue;
    private fnOnEscape;
    private fnWaitSound;
    private fnWaitKey;
    private fnWaitInput;
    private static parseLineNumber;
    private static addLineNumbers;
    private splitLines;
    private mergeScripts;
    private fnGetLinesInRange;
    private static fnPrepareMaskRegExp;
    private fnGetExampleDirectoryEntries;
    private static fnGetStorageDirectoryEntries;
    private fnPrintDirectoryEntries;
    private fnFileCat;
    private fnFileDir;
    private fnFileEra;
    private fnFileRen;
    private static asmGena3Convert;
    private getBasicFormatter;
    private getBasicTokenizer;
    private getCodeGeneratorBasic;
    private getCodeGeneratorToken;
    private decodeTokenizedBasic;
    private encodeTokenizedBasic;
    private prettyPrintBasic;
    private static gaInk2Ink;
    private applyGaInks;
    private applyCrtcRegs;
    private applySnapshot;
    private loadFileContinue;
    private createFnExampleLoaded;
    private createFnExampleError;
    private loadExample;
    private static fnLocalStorageName;
    private static defaultExtensions;
    private static tryLoadingFromLocalStorage;
    private fnFileLoad;
    private static splitMeta;
    private fnFileSave;
    private fnDeleteLines;
    private fnNew;
    private fnList;
    private fnReset;
    private outputError;
    private fnRenumLines;
    private fnEditLineCallback;
    private fnEditLine;
    private fnParseBench;
    private fnParse;
    fnPretty(): void;
    fnAddLines(): void;
    fnRemoveLines(): void;
    private fnGetFilename;
    fnDownload(): void;
    private selectJsError;
    private fnChain;
    private fnRun;
    private fnParseRun;
    private fnParseChain;
    private fnRunPart1;
    private fnDirectInput;
    private startWithDirectInput;
    private updateResultText;
    private exitLoop;
    private fnWaitFrame;
    private fnOnError;
    private static fnDummy;
    private fnTimer;
    private fnRunLoop;
    startMainLoop(): void;
    private setStopObject;
    private getStopObject;
    startParse(): void;
    startRenum(): void;
    startRun(): void;
    startParseRun(): void;
    startBreak(): void;
    startContinue(): void;
    startReset(): void;
    startScreenshot(): string;
    private fnPutKeysInBuffer;
    startEnter(): void;
    private static generateFunction;
    changeVariable(): void;
    setBasicVersion(basicVersion: string): void;
    setPalette(palette: string): void;
    setCanvasType(canvasType: string): ICanvas;
    setSoundActive(): void;
    private getZ80Disass;
    setDisassAddr(addr: number, endAddr?: number): void;
    private fnEndOfImport;
    private static fnOnDragover;
    private adaptFilename;
    private getFileHandler;
    private getFileSelect;
    private initDropZone;
    private fnUpdateUndoRedoButtons;
    private fnInitUndoRedoButtons;
    private fnPutChangedInputOnStack;
    startUpdateCanvas(): void;
    stopUpdateCanvas(): void;
    private getDragElement;
    getVirtualKeyboard(): VirtualKeyboard;
    private dragElementsData;
    fnDragElementsActive(enabled: boolean): void;
    getVariable(par: string): VariableValue;
    undoStackElement(): string;
    redoStackElement(): string;
    private createFnDatabaseLoaded;
    private createFnDatabaseError;
    onDatabaseSelectChange(): void;
    onDirectorySelectChange(): void;
    onExampleSelectChange(): void;
    exportAsBase64(storageName: string): string;
    onCpcCanvasClick(event: MouseEvent): void;
    onWindowClick(event: Event): void;
    fnArrayBounds(): void;
    fnImplicitLines(): void;
    fnTrace(): void;
    fnSpeed(): void;
    private readonly handlers;
}
//# sourceMappingURL=Controller.d.ts.map